apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-api-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager-role
  namespace: default
rules:
  - apiGroups: [""] # "" means the core API group
    # --- THIS IS THE UPDATED LINE ---
    resources: ["pods", "pods/log", "pods/status"] 
    verbs: ["create", "get", "list", "watch", "delete", "stream"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: task-api-account
    namespace: default 
roleRef:
  kind: Role
  name: pod-manager-role
  apiGroup: rbac.authorization.k8s.io